name: dimred_tutorial
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib=3.5.1
  - scipy
  - scikit-learn
  - ipykernel
  - pip
  - pip:
      - mat73
      - ica
      - ipympl
